[tox]
skipsdist = True
skip_missing_interpreters = True
envlist =
    prepare
    py{36,37,38,39,310,311,312,313,314,315}
    report

[testenv:py37]
base_python = python3.7
virtualenv_spec = virtualenv<20.22.0

[testenv:py36]
base_python = python3.6
virtualenv_spec = virtualenv<20.22.0

[testenv]
passenv =
    CFLAGS
    CPPFLAGS
    LDFLAGS
    PKG_CONFIG_PATH
commands =
    ./run.sh

[testenv:prepare]
commands =
    ./prepare.sh

[testenv:report]
commands =
    ./report.sh


# vim: nowrap
